version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:1.11.3
    container_name: selenoid
    ports:
      - "4444:4444"
    volumes:
      - ./browser.json:/etc/selenoid/browsers.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/tmp/video
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video",
      "-log-output-dir", "/opt/selenoid/logs",
      "-container-network", "sprint_9_default"
    ]
    networks:
      - selenoid

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    environment:
      - SELENOID_URL=http://selenoid:4444
    depends_on:
      - selenoid
    networks:
      - selenoid

  tests:
    build: .
    depends_on:
      - selenoid
    environment:
      - SELENOID_URI=http://selenoid:4444/wd/hub
      - USE_REMOTE_DRIVER=true
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - selenoid

networks:
  selenoid:
    name: sprint_9_default
    driver: bridge
